### ISSUE TITLE
How did you determine whether to throw an exception or simply return a Boolean?

### ISSUE THREAD

**Issue by lgtout** [overfullstack/railway-oriented-validation-kotlin#2]
Hi, Gopal.

In the rules, how did you determine whether to throw an exception or simply return a Boolean?  Or was it arbitrary, for the purpose of simply having cases where both sorts of validation outcomes are possible?  For example, a bad yolk causes an exception, though I expected validation would return false.

Thanks!

**Comment by overfullstack** [comment]
Yes, those are just some dummy rules to get all the outcomes for demonstration. You can tweak them as per your understanding, but they don't contribute to the idea that I am trying to express through this repo.
